from tkinter import*
def fill():
    first=entry1.get()
    if first=="":
        label0=Label(root,text="FILL LOGIN ID ?",bg="white",fg="red",font=("Areal",9))
        label0.place(x=600,y=340)
    second=entry2.get()
    if second=="":
        label00=Label(root,text="FILL PASSWORD ?",bg="white",fg="red",font=("Areal",9))
        label00.place(x=600,y=450)
root=Tk()
root.geometry("1400x800")
title=root.title("UNITECH LOGIN")
frame=Frame(root,bg="white",borderwidth=5,relief="solid",height=400,width=500)
label1=Label(root,text="Access To Login",bg="white",fg="blue",font=("Areal",20))
label1.place(x=640,y=180)
label4=Label(root,text="Welcome To UNI Tech Login..",bg="white",fg="orange",font=("Areal",9))
label4.place(x=660,y=220)
label2=Label(root,text="Login Id",bg="white",font=("Areal",15))
label2.place(x=600,y=260)
entry1=Entry(root,borderwidth=2,relief="solid",font=("Areal",15))
entry1.place(x=600,y=310)
label3=Label(root,text="Password",bg="white",font=("Areal",15))
label3.place(x=600,y=370)
entry2=Entry(root,borderwidth=2,relief="solid",show="*",font=("Areal",15))
entry2.place(x=600,y=420)
button=Button(root,text="LOGIN",borderwidth=5,relief="raised",activebackground="red",fg="white",bg="blue",font=("Areal",15),command=fill)
button.place(x=600,y=480)
label3=Label(root,text="unitechteam@gmail.com",fg="red",font=("Areal",9))
label3.place(x=10,y=650)
label4=Label(root,text="Customer Care : 030333424453",fg="red",font=("Areal",9))
label4.place(x=10,y=670)
frame.place(x=510,y=160)
root.mainloop()
